# Generated by Django 4.0.2 on 2022-05-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0002_alter_material_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
