# Generated by Django 4.0.2 on 2022-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0003_pedido_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='rentabilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total_costos',
            field=models.IntegerField(default=0),
        ),
    ]
