# Generated by Django 4.0.2 on 2022-06-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0005_trabajo_total_simp_trabajo_total_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='total_pago',
            field=models.IntegerField(default=0),
        ),
    ]
