# Generated by Django 4.0.2 on 2022-07-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0006_trabajo_total_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reserva_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
