# Generated by Django 4.0.2 on 2022-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0007_pedido_reserva_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='abono',
            field=models.IntegerField(default=0),
        ),
    ]
